CREATE TABLE devices (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status ENUM('ONLINE', 'OFFLINE', 'ERROR') DEFAULT 'OFFLINE',
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    metadata JSON
);