spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092

security:
  jwt:
    secret: "your_secret_key"
